#!/usr/bin/env python
#coding:utf-8
from dynamo import *

#informacion general
simulation="SNAP"
numsnapshot="000"
simfile="%s_%s.sim"%(simulation,numsnapshot)

"""
################################################
1- convertir gadget a ascii
################################################
"""
print "\n######################################################"
print "This script calculates the surface density with dynamo"
print "######################################################\n"

if not isfile(simfile):
    print "Becoming from binary to ascii...",
    shellExec(RUN+"bin2sim.out -s %s -n %s -S"%(simulation,numsnapshot))
    print "Done."
    print "Updating header...",
    shellExec(RUN+"updatesim.out -f %s"%simfile)
    print "Done."
else:
    print "The file of simulation '%s' already exist..."%simfile
"""
################################################
2- transformar todo al CM del sistema
################################################
"""

"""
################################################
3- actualizar el header
################################################
"""

"""
################################################
4- filtar las partículas en el disco
################################################
"""

"""
################################################
5- hacer un mapeo escalar (mass_density)
################################################
"""

"""
################################################
6- hacer una juste a la función del paper de 
Herquist
################################################
"""

"""
################################################
7- graficar la superposición de la densidad calculada 
y el ajuste
################################################
"""
