#!/usr/bin/env python
#coding:utf-8
from dynamo import *

#informacion general
simulation="MW_clues_10909_1.63_1_eq_HQ_WB_MMP"
numsnapshot="000"
simfile="%s_%s.sim"%(simulation,numsnapshot)

"""
################################################
1- convertir gadget a ascii
################################################
"""
print "\n######################################################"
print "This script calculates the surface density with dynamo"
print "######################################################\n"

if not isfile(simfile):
    print "Becoming from binary to ascii..."
    shellExec(RUN+"bin2sim.out -V -s %s -n %s -S"%(simulation,numsnapshot))
    print "Done."
    print "Updating header...\t"
    shellExec(RUN+"updatesim.out -f %s"%simfile)
    print "Done."
else:
    print "The file of simulation '%s' already exist..."%simfile
"""
################################################
2- transformar todo al CM del sistema
################################################
"""
newfile="%s.trn"%simfile
if not isfile(newfile):
    print "Transforming to CM of the system into '%s'..."%newfile
    poscm=getHeader(simfile,"POSIT.CM")
    velcm=getHeader(simfile,"VELOC.CM")
    angmom=getHeader(simfile,"ANG.MOM.TOT")
    shellExec(RUN+"transform.out -V -s %s -t %s -o %s -e %s -j %s -l 1"%(simfile,
                                                                        newfile,
                                                                        ",".join(poscm),
                                                                        ",".join(velcm),
                                                                        ",".join(angmom)))
    print "Done."
    print "updating header..."
    shellExec(RUN+"updatesim.out -f %s"%newfile)
    print "Done."
else:
    print "The fILE '%s' already exist..."%newfile
simfile=newfile

"""
#################################################
4- filtar las particulas correspondientes al 
bulbo y disco
#################################################
"""
"""
filtro las particulas de disco y bulbo
"""
newfile="%s.fil"%simfile
print "filtering the particles of disk and bulge in '%s'..."%newfile
shellExec(RUN+"filter.out -f %s -s %s -n 25 -c 4 -m 2 -M 3"%(simfile,newfile))
print "Done"
simfile=newfile
"""

Estadistica sobre epsilon para las particulas de disco y bulbo
"""
print "making statistics for epsilon in '%s.his'..."%simfile
shellExec(RUN+"stats.out -V -f %s -s %s.his -n25 -c 25 -b 200 -t l"%(simfile,simfile))
print "Done."

"""
ajusto los pocos a dos gaussianas
"""
print "ajusting epsilon to one gaussian 0 center in '%s.his.fit0'..."%simfile
shellExec(RUN+"fit.out -V -f %s.his -F %s.his.fit0 -u gaussianBell -p 1.0,0.0,1.0 -n 11 -x 2 -y 4 -e 7"%(simfile,simfile))
print "Done."

print "ajusting epsilon to one gaussian 1 center in '%s.his.fit1'..."%simfile
shellExec(RUN+"fit.out -V -f %s.his -F %s.his.fit1 -u gaussianBell -p 1.0,1.0,1.0 -n 11 -x 2 -y 4 -e 7"%(simfile,simfile))
print "Done."

"""
separo las particulas del bulbo y disco con un criterio a ojo en 
el epsilon
"""
"""
print "filtering the particles of disk '%s.disk'..."%simfile
shellExec(RUN+"filter.out -f %s -s %s.disk -n 25 -c 25 -m 0.4"%(simfile,simfile))
print "Done"

print "filtering the particles of disk '%s.disk'..."%simfile
shellExec(RUN+"filter.out -f %s -s %s.disk -n 25 -c 25 -m 0.4"%(simfile,simfile))
print "Done"
"""
"""
#########################################################
4- corte a la bruta para extraer las partículas del disco
#########################################################
"""
"""
check,status=shellExec("grep -v '#' %s | awk '{print $13,$25}'"%simfile)
print check

epscrit=input("critical value of epsilon:")
newfile="%s.%.2e.fill"%(simfile,epscrit)
"""
"""
################################################
4- filtar las partículas en el disco
################################################
"""

"""
################################################
5- hacer un mapeo escalar (mass_density)
################################################
"""

"""
################################################
6- hacer una juste a la función del paper de 
Herquist
################################################
"""

"""
################################################
7- graficar la superposición de la densidad calculada 
y el ajuste
################################################
"""
