#!/usr/bin/env python
#coding:encode:utf-8
from dynamo import *

#informacion general
simulation="SNAP"
numsnapshot="000"
simfile=="%s_%s.sim"%(simulation,numsnapshot)

"""
################################################
1- convertir gadget a ascii
################################################
"""

"""
################################################
2- transformar todo al CM del sistema
################################################
"""

"""
################################################
3- actualizar el header
################################################
"""

"""
################################################
4- filtar las partículas en el disco
################################################
"""

"""
################################################
5- hacer un mapeo escalar (mass_density)
################################################
"""

"""
################################################
6- hacer una juste a la función del paper de 
Herquist
################################################
"""

"""
################################################
7- graficar la superposición de la densidad calculada 
y el ajuste
################################################
"""
